name = "gnat_math_extensions"
description = "Eigenvalues, eigenvectors for non-symmetric, non-Hermitian matrices"
website = "https://github.com/simonjwright/gnat_math_extensions"
version = "1.1.0"
licenses= "GPL-3.0-or-later WITH GCC-exception-3.1"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

project-files = ["gnat_math_extensions.gpr"]

tags = ["matrices", "blas", "lapack"]

# The package may work on Windows using different BLAS/Lapack packages
# than those available to Alire under msys2, which won't load (keyring
# errors: 2022-05-15)
[available.'case(os)']
  linux = true
  macos = true
  windows = false

# BLAS, Lapack are provided with macOS Xcode or Command Line Tools.
[[depends-on]]
[depends-on.'case(os)'.linux]
  "libblas" = "*"
  "liblapack" = "*"
