---

name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: alire-project/setup-alire
      uses: alire-project/setup-alire@v1
    -
      name: Build and run tests
      run: |
        alr config --global --set toolchain.assistant false
        alr toolchain --install gnat_native --non-interactive
        alr toolchain --install gprbuild --non-interactive
        alr toolchain --select gnat_native --non-interactive
        alr toolchain --select gprbuild --non-interactive
        cd test; alr run --non-interactive
