---
name: Build

on:
  push:
    branches: [ alire-workflows ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
#          - macos-latest
#          - windows-latest
          - debian-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    # -
    #   name: ada-actions/toolchain
    #   uses: ada-actions/toolchain@ce2020
    #   with:
    #     distrib: community
    #     target: native
    -
      name: alire-project/setup-alire
      uses: alire-project/setup-alire@latest-stable
    -
      name: Build
      run: |
        alr index --reset-community
        echo "adding local index"
        alr index --name=local --add=git+https://github.com/simonjwright/local-alire-index.git
        echo "setting toolchain.assistant false"
        alr config --global --set toolchain.assistant false
        echo "installing toolchain"
        alr toolchain --install gnat_native --non-interactive
        alr toolchain --install gprbuild --non-interactive
        echo "selecting toolchain"
        alr toolchain --select gnat_native --non-interactive
        alr toolchain --select gprbuild --non-interactive
        echo "building!"
        alr build --non-interactive
