---
name: Build

on:
  push:
    branches: [ alire-workflows ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: alire-project/setup-alire
      uses: alire-project/setup-alire@latest-stable
    -
      name: Build
      run: |
        alr index --reset-community
        echo "adding local index"
        alr index --name=local --add=git+https://github.com/simonjwright/local-alire-index.git
        echo "setting toolchain.assistant false"
        alr config --global --set toolchain.assistant false
        echo "installing toolchain"
        alr toolchain --install gnat_native --non-interactive
        alr toolchain --install gprbuild --non-interactive
        echo "selecting toolchain"
        alr toolchain --select gnat_native --non-interactive
        alr toolchain --select gprbuild --non-interactive
        echo "building/running!"
        cd test; alr run --non-interactive
